packages:
  - .
  - bundler

allowBuilds:
  electron: true
  esbuild: false
  workerd: false

enableGlobalVirtualStore: false

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

lockfileIncludeTarballUrl: true

overrides:
  '@eslint/eslintrc>espree': ^10.4.0
  eslint>espree: ^10.4.0

preferWorkspacePackages: true
