packages:
  - .
  - bundler

enableGlobalVirtualStore: false

ignoreWorkspaceRootCheck: true

linkWorkspacePackages: true

lockfileIncludeTarballUrl: true

onlyBuiltDependencies:
  - electron
  - esbuild
  - workerd

overrides:
  eslint>espree: ^10.4.0
  '@eslint/eslintrc>espree': ^10.4.0

preferWorkspacePackages: true
